#!/bin/bash
# Boundary checkpoint (2026-09-04, platform ops): public operator tooling.
# Public-safe abstractions only; node identities, credentials, provider account
# detail and cost data stay in internal-devops.
# Policy: docs/PUBLIC_REPO_BOUNDARY.md

# =============================================================================
#  HISTORICAL — DO NOT RUN AGAINST MADFAM PRODUCTION.  Superseded 2026.
#  Reviewed 2026-07-25.
#
#  This script is part of the 2025-12-02 single-host bootstrap: it provisioned
#  ONE Ubuntu server running Docker Compose with a ZFS storage driver.
#
#  MADFAM production is now bare-metal k3s with ArgoCD GitOps. Images are built
#  by CI, pushed to GHCR, pinned by digest into kustomization.yaml, and pulled
#  by ArgoCD. Nothing is built or deployed on the server. Services are onboarded
#  with `enclii onboard`. ArgoCD runs with selfHeal enabled, so hand-applied
#  changes are reverted.
#
#  Kept as a record of how the estate actually ran, and because the ZFS tuning
#  and SSH hardening here remain useful reference. See ../README.md for the
#  current model, and the private internal-devops repo for real procedures.
# =============================================================================
set -euo pipefail

# Solarpunk Foundry - SSH Hardening Script
# Target node: see internal-devops for production SSH inventory
# Purpose: Harden SSH access and prepare for Cloudflare Zero Trust migration

echo "==============================================="
echo "  SOLARPUNK FOUNDRY - SSH HARDENING"
echo "  Phase 5: Security Hardening"
echo "==============================================="

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# The operator account name is maintained privately (internal-devops); it is never
# published in this public repo (placeholdered 2026-09-23, coherence audit B-C04).
OPERATOR_USER="${OPERATOR_USER:?set OPERATOR_USER to the operator account name}"

# Backup original SSH config
log_step "1/6 - Backing up SSH configuration..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)
log_info "Backup created"

# Configure SSH hardening
log_step "2/6 - Hardening SSH configuration..."

# Create hardened SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# Solarpunk Foundry SSH Hardening Configuration
# Generated by 05-ssh-hardening.sh

# ============================================
# AUTHENTICATION
# ============================================

# Disable root login (use operator user (<OPERATOR_USER>) with sudo)
PermitRootLogin no

# Only allow specific users
AllowUsers __OPERATOR_USER__

# Disable password authentication (key-only)
PasswordAuthentication no
PermitEmptyPasswords no

# Enable public key authentication
PubkeyAuthentication yes

# Disable challenge-response authentication
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no

# ============================================
# SECURITY HARDENING
# ============================================

# Use strong key exchange algorithms
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Use strong ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Use strong MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# Disable X11 forwarding (not needed for server)
X11Forwarding no

# Disable TCP forwarding (enable only if needed)
AllowTcpForwarding no

# Disable agent forwarding
AllowAgentForwarding no

# Disable tunneling
PermitTunnel no

# ============================================
# SESSION MANAGEMENT
# ============================================

# Reduce login grace time
LoginGraceTime 30

# Maximum authentication attempts
MaxAuthTries 3

# Maximum sessions per connection
MaxSessions 3

# Client alive interval (detect dead connections)
ClientAliveInterval 300
ClientAliveCountMax 2

# ============================================
# LOGGING
# ============================================

# Enhanced logging
LogLevel VERBOSE

# Log SFTP activity
Subsystem sftp /usr/lib/openssh/sftp-server -l INFO

# ============================================
# NETWORK
# ============================================

# Listen only on IPv4 (adjust if IPv6 needed)
AddressFamily inet

# Default port (will be closed after Cloudflare Tunnel is active)
Port 22
EOF
# The account name is not published; it is supplied at run time.
sed -i "s/__OPERATOR_USER__/${OPERATOR_USER}/" /etc/ssh/sshd_config.d/99-hardening.conf

log_info "SSH hardening configuration created"

# Ensure operator user (<OPERATOR_USER>) exists and has SSH access
log_step "3/6 - Configuring operator user (<OPERATOR_USER>)..."

if ! id -u "${OPERATOR_USER}" &>/dev/null; then
    log_info "Creating operator user (<OPERATOR_USER>)..."
    useradd -m -s /bin/bash "${OPERATOR_USER}"
    usermod -aG sudo "${OPERATOR_USER}"
    usermod -aG docker "${OPERATOR_USER}"
fi

# Copy root's authorized_keys to ${OPERATOR_USER}
if [ -f /root/.ssh/authorized_keys ]; then
    mkdir -p /home/${OPERATOR_USER}/.ssh
    cp /root/.ssh/authorized_keys /home/${OPERATOR_USER}/.ssh/
    chown -R "${OPERATOR_USER}:${OPERATOR_USER}" /home/${OPERATOR_USER}/.ssh
    chmod 700 /home/${OPERATOR_USER}/.ssh
    chmod 600 /home/${OPERATOR_USER}/.ssh/authorized_keys
    log_info "SSH keys copied to operator user (<OPERATOR_USER>)"
else
    log_warn "No authorized_keys found for root - you'll need to add SSH keys for ${OPERATOR_USER} manually"
fi

# Configure fail2ban for SSH
log_step "4/6 - Configuring fail2ban..."

cat > /etc/fail2ban/jail.d/sshd.conf << 'EOF'
# Solarpunk Foundry - SSH fail2ban configuration
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
ignoreip = 127.0.0.1/8

# More aggressive settings for repeated offenders
[sshd-aggressive]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 86400
findtime = 3600
EOF

log_info "fail2ban configured"

# Verify SSH configuration
log_step "5/6 - Validating SSH configuration..."

if sshd -t; then
    log_info "SSH configuration is valid"
else
    log_error "SSH configuration is invalid! Rolling back..."
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

# Restart services
log_step "6/6 - Restarting services..."

systemctl restart sshd
systemctl restart fail2ban

log_info "SSH and fail2ban restarted"

# Final status
echo ""
echo "==============================================="
echo "  SSH HARDENING COMPLETE"
echo "==============================================="
echo ""
echo "Changes applied:"
echo "  ✓ Root login disabled"
echo "  ✓ Only '${OPERATOR_USER}' user can SSH"
echo "  ✓ Password authentication disabled"
echo "  ✓ Strong encryption algorithms enforced"
echo "  ✓ fail2ban configured (3 attempts = 1 hour ban)"
echo ""
echo -e "${YELLOW}IMPORTANT:${NC}"
echo "  1. Test SSH access with operator user (<OPERATOR_USER>) BEFORE closing this session:"
echo "     ssh -i ~/.ssh/id_ed25519 <OPERATOR_USER>@<BOOTSTRAP_HOST>"
echo ""
echo "  2. operator user (<OPERATOR_USER>) has sudo access - use 'sudo' for admin commands"
echo ""
echo "  3. Once Cloudflare Zero Trust SSH is configured, close port 22:"
echo "     ufw delete allow 22/tcp"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  - Set up the Zero Trust SSH DNS record documented in internal-devops"
echo "  - Configure Zero Trust Access policy"
echo "  - Test SSH via Cloudflare Tunnel"
echo "  - Close port 22"
echo ""
