#!/bin/bash
set -euo pipefail

# Solarpunk Foundry - SSH Hardening Script
# Server: Hetzner AX41-NVMe (95.217.198.239)
# Purpose: Harden SSH access and prepare for Cloudflare Zero Trust migration

echo "==============================================="
echo "  SOLARPUNK FOUNDRY - SSH HARDENING"
echo "  Phase 5: Security Hardening"
echo "==============================================="

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Backup original SSH config
log_step "1/6 - Backing up SSH configuration..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)
log_info "Backup created"

# Configure SSH hardening
log_step "2/6 - Hardening SSH configuration..."

# Create hardened SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# Solarpunk Foundry SSH Hardening Configuration
# Generated by 05-ssh-hardening.sh

# ============================================
# AUTHENTICATION
# ============================================

# Disable root login (use solarpunk user with sudo)
PermitRootLogin no

# Only allow specific users
AllowUsers solarpunk

# Disable password authentication (key-only)
PasswordAuthentication no
PermitEmptyPasswords no

# Enable public key authentication
PubkeyAuthentication yes

# Disable challenge-response authentication
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no

# ============================================
# SECURITY HARDENING
# ============================================

# Use strong key exchange algorithms
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Use strong ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Use strong MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# Disable X11 forwarding (not needed for server)
X11Forwarding no

# Disable TCP forwarding (enable only if needed)
AllowTcpForwarding no

# Disable agent forwarding
AllowAgentForwarding no

# Disable tunneling
PermitTunnel no

# ============================================
# SESSION MANAGEMENT
# ============================================

# Reduce login grace time
LoginGraceTime 30

# Maximum authentication attempts
MaxAuthTries 3

# Maximum sessions per connection
MaxSessions 3

# Client alive interval (detect dead connections)
ClientAliveInterval 300
ClientAliveCountMax 2

# ============================================
# LOGGING
# ============================================

# Enhanced logging
LogLevel VERBOSE

# Log SFTP activity
Subsystem sftp /usr/lib/openssh/sftp-server -l INFO

# ============================================
# NETWORK
# ============================================

# Listen only on IPv4 (adjust if IPv6 needed)
AddressFamily inet

# Default port (will be closed after Cloudflare Tunnel is active)
Port 22
EOF

log_info "SSH hardening configuration created"

# Ensure solarpunk user exists and has SSH access
log_step "3/6 - Configuring solarpunk user..."

if ! id -u solarpunk &>/dev/null; then
    log_info "Creating solarpunk user..."
    useradd -m -s /bin/bash solarpunk
    usermod -aG sudo solarpunk
    usermod -aG docker solarpunk
fi

# Copy root's authorized_keys to solarpunk
if [ -f /root/.ssh/authorized_keys ]; then
    mkdir -p /home/solarpunk/.ssh
    cp /root/.ssh/authorized_keys /home/solarpunk/.ssh/
    chown -R solarpunk:solarpunk /home/solarpunk/.ssh
    chmod 700 /home/solarpunk/.ssh
    chmod 600 /home/solarpunk/.ssh/authorized_keys
    log_info "SSH keys copied to solarpunk user"
else
    log_warn "No authorized_keys found for root - you'll need to add SSH keys for solarpunk manually"
fi

# Configure fail2ban for SSH
log_step "4/6 - Configuring fail2ban..."

cat > /etc/fail2ban/jail.d/sshd.conf << 'EOF'
# Solarpunk Foundry - SSH fail2ban configuration
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
ignoreip = 127.0.0.1/8

# More aggressive settings for repeated offenders
[sshd-aggressive]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 86400
findtime = 3600
EOF

log_info "fail2ban configured"

# Verify SSH configuration
log_step "5/6 - Validating SSH configuration..."

if sshd -t; then
    log_info "SSH configuration is valid"
else
    log_error "SSH configuration is invalid! Rolling back..."
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

# Restart services
log_step "6/6 - Restarting services..."

systemctl restart sshd
systemctl restart fail2ban

log_info "SSH and fail2ban restarted"

# Final status
echo ""
echo "==============================================="
echo "  SSH HARDENING COMPLETE"
echo "==============================================="
echo ""
echo "Changes applied:"
echo "  ✓ Root login disabled"
echo "  ✓ Only 'solarpunk' user can SSH"
echo "  ✓ Password authentication disabled"
echo "  ✓ Strong encryption algorithms enforced"
echo "  ✓ fail2ban configured (3 attempts = 1 hour ban)"
echo ""
echo -e "${YELLOW}IMPORTANT:${NC}"
echo "  1. Test SSH access with solarpunk user BEFORE closing this session:"
echo "     ssh -i ~/.ssh/id_ed25519 solarpunk@95.217.198.239"
echo ""
echo "  2. solarpunk user has sudo access - use 'sudo' for admin commands"
echo ""
echo "  3. Once Cloudflare Zero Trust SSH is configured, close port 22:"
echo "     ufw delete allow 22/tcp"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  - Set up ssh.madfam.io DNS (CNAME to tunnel)"
echo "  - Configure Zero Trust Access policy"
echo "  - Test SSH via Cloudflare Tunnel"
echo "  - Close port 22"
echo ""
