#cloud-config
# Janua API Server Initialization
# ===============================

hostname: ${node_name}

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl
  - jq
  - htop
  - fail2ban
  - ufw

write_files:
  # Docker daemon configuration
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }

  # Janua environment configuration
  - path: /opt/janua/.env
    permissions: "0600"
    content: |
      # Janua Configuration
      DATABASE_URL=${database_url}
      REDIS_URL=${redis_url}
      JWT_SECRET=${jwt_secret}

      # Server settings
      API_HOST=0.0.0.0
      API_PORT=8000
      ENVIRONMENT=${environment}

      # Domain configuration
      API_DOMAIN=${api_domain}
      CORS_ORIGINS=https://${api_domain},https://app.enclii.dev

      # Feature flags
      ENABLE_ADMIN=true
      ENABLE_METRICS=true

      # Logging
      LOG_LEVEL=INFO
      LOG_FORMAT=json

  # Docker compose for Janua
  - path: /opt/janua/docker-compose.yml
    content: |
      version: '3.8'

      services:
        janua-api:
          image: ghcr.io/madfam/janua:latest
          container_name: janua-api
          restart: unless-stopped
          ports:
            - "8000:8000"
          env_file:
            - .env
          healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
          logging:
            driver: json-file
            options:
              max-size: "10m"
              max-file: "3"
          deploy:
            resources:
              limits:
                memory: 512M
              reservations:
                memory: 256M

        cloudflared:
          image: cloudflare/cloudflared:latest
          container_name: cloudflared
          restart: unless-stopped
          command: tunnel run
          environment:
            - TUNNEL_TOKEN=$${TUNNEL_TOKEN}
          depends_on:
            - janua-api
          logging:
            driver: json-file
            options:
              max-size: "5m"
              max-file: "2"

  # Systemd service for Janua
  - path: /etc/systemd/system/janua.service
    content: |
      [Unit]
      Description=Janua Authentication Service
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/janua
      ExecStart=/usr/bin/docker-compose up -d
      ExecStop=/usr/bin/docker-compose down

      [Install]
      WantedBy=multi-user.target

  # UFW rules setup script
  - path: /opt/scripts/setup-firewall.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      # Reset UFW
      ufw --force reset

      # Default policies
      ufw default deny incoming
      ufw default allow outgoing

      # Allow SSH only from private network
      ufw allow from 10.1.0.0/16 to any port 22

      # Allow internal traffic
      ufw allow from 10.1.0.0/16

      # Allow Docker internal
      ufw allow from 172.17.0.0/16

      # Enable UFW
      ufw --force enable

      echo "Firewall configured"

  # Health check script
  - path: /opt/scripts/health-check.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      check_service() {
        if curl -sf http://localhost:8000/health > /dev/null; then
          echo "✅ Janua API: healthy"
          return 0
        else
          echo "❌ Janua API: unhealthy"
          return 1
        fi
      }

      check_docker() {
        if docker ps --filter "name=janua-api" --filter "status=running" | grep -q janua-api; then
          echo "✅ Docker container: running"
          return 0
        else
          echo "❌ Docker container: not running"
          return 1
        fi
      }

      echo "=== Janua Health Check ==="
      check_docker
      check_service

runcmd:
  # Enable and start Docker
  - systemctl enable docker
  - systemctl start docker

  # Create janua user
  - useradd -r -s /bin/false janua || true
  - usermod -aG docker janua

  # Set permissions
  - chown -R janua:janua /opt/janua
  - chmod 700 /opt/janua

  # Setup firewall
  - /opt/scripts/setup-firewall.sh

  # Enable fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # Pull latest Janua image
  - docker pull ghcr.io/madfam/janua:latest || echo "Image will be pulled on first start"

  # Enable and start Janua service
  - systemctl enable janua
  - systemctl start janua

  # Log completion
  - echo "Janua API server initialization complete" | tee /var/log/cloud-init-janua.log

final_message: "Janua API server ${node_name} ready after $UPTIME seconds"
