/**
 * GENERATED FILE - DO NOT EDIT BY HAND.
 *
 * Rendered from packages/core/src/products/projection.public.json by
 * scripts/check-product-projection.mjs. That JSON is the public-safe projection
 * of the private product registry; edit the registry, re-run the private
 * generator, re-vendor the projection, then run this script with --write.
 *
 * A hand edit here is reverted by the next run and fails Package Quality.
 *
 * The hand-kept half of the module - the `Product` type, the licence and layer
 * vocabularies and every lookup - lives next door in `products.ts`.
 */

/** The projection stamp, carried so a consumer can tell which registry version it holds. */
export const PRODUCT_PROJECTION = {
  schema: "madfam-product-projection/v1",
  generatedFrom: "internal-devops/ecosystem/registry/products.yaml",
  registryVersion: 4,
  lastUpdated: "2026-09-05",
  exportPrivateRepoNames: true,
  /** sha256 of the vendored projection.public.json this module was rendered from. */
  sourceSha256: "b9a1a315eedcb1c3c3cf13fc7c8c17a0fa12048f51750488885192594091cb6e",
} as const;

/**
 * Every renderable product, keyed by registry slug, in registry order.
 * Retired products are NOT here by construction - see `generatedRetiredProducts`.
 */
export const generatedProducts = {
  enclii: {
    id: "enclii",
    name: "Enclii",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "soil",
    repo: "enclii",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "enclii.dev",
    hosts: [
      "app.enclii.dev",
      "api.enclii.dev",
      "admin.enclii.dev",
      "status.enclii.dev",
      "docs.enclii.dev",
    ],
    infraHosts: [
      "npm.madfam.io",
      "status.madfam.io",
      "grafana.enclii.dev",
      "prometheus.enclii.dev",
      "alertmanager.enclii.dev",
    ],
    site: {
      category: "Infrastructure",
      track: "platform",
      order: 1,
      icon: "☁️",
      bannerKeyword: "DEPLOYMENT",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "community",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  janua: {
    id: "janua",
    name: "Janua",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "soil",
    repo: "janua",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "janua.dev",
    hosts: [
      "docs.janua.dev",
    ],
    infraHosts: [
      "auth.madfam.io",
    ],
    site: {
      category: "Infrastructure",
      track: "platform",
      order: 2,
      icon: "🔐",
      bannerKeyword: "AUTHENTICATION",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "community",
        "pro",
        "enterprise",
      ],
      adminTier: "admin",
    },
  },
  selva: {
    id: "selva",
    name: "Selva",
    aliases: [
      "Selva Office",
    ],
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "selva-office",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "selva.town",
    hosts: [
      "www.selva.town",
      "app.selva.town",
      "api.selva.town",
      "admin.selva.town",
      "ws.selva.town",
      "gw.selva.town",
    ],
    infraHosts: [
      "inference.selva.town",
    ],
    site: {
      category: "Infrastructure",
      track: "platform",
      order: 3,
      icon: "🌳",
      bannerKeyword: "AI AGENT OFFICE",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "maker",
        "studio",
        "enterprise",
      ],
      adminTier: "admin",
      checkoutSlug: "selva",
    },
  },
  forgesight: {
    id: "forgesight",
    name: "Forgesight",
    aliases: [
      "Forge Sight",
      "ForgeSight",
    ],
    siteSlug: "forge-sight",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    dataLicense: "DATA_LICENSE",
    layer: "roots",
    repo: "forgesight",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "forgesight.quest",
    hosts: [
      "app.forgesight.quest",
      "api.forgesight.quest",
      "admin.forgesight.quest",
    ],
    infraHosts: [],
    site: {
      category: "Intelligence",
      track: "self-serve",
      order: 4,
      icon: "🏭",
      bannerKeyword: "INDUSTRY INTELLIGENCE",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "essentials",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
      checkoutSlug: "forgesight",
    },
  },
  dhanam: {
    id: "dhanam",
    name: "Dhanam",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "dhanam",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    openCoreRepo: "dhanam-core",
    isPublic: false,
    domain: "dhan.am",
    hosts: [
      "app.dhan.am",
      "api.dhan.am",
      "admin.dhan.am",
    ],
    infraHosts: [],
    site: {
      category: "Intelligence",
      track: "self-serve",
      order: 5,
      icon: "💰",
      bannerKeyword: "BUDGETING & WEALTH",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "community",
        "essentials",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
      checkoutSlug: "dhanam",
    },
  },
  fortuna: {
    id: "fortuna",
    name: "Fortuna",
    lifecycle: "degraded",
    lifecycleVerified: "2026-08-24",
    license: "Proprietary",
    layer: "roots",
    repo: "fortuna",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "fortuna.tube",
    hosts: [
      "api.fortuna.tube",
    ],
    infraHosts: [],
    site: {
      category: "Intelligence",
      track: "self-serve",
      order: 6,
      icon: "🔮",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  rondelio: {
    id: "rondelio",
    name: "Rondelio",
    lifecycle: "live",
    lifecycleVerified: "2026-07-09",
    license: "Proprietary",
    layer: "fruit",
    repo: "rondelio",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "rondel.io",
    hosts: [
      "www.rondel.io",
      "api.rondel.io",
      "play.rondel.io",
      "studio.rondel.io",
      "admin.rondel.io",
      "sim.rondel.io",
    ],
    infraHosts: [],
    site: {
      category: "Intelligence",
      track: "self-serve",
      order: 7,
      icon: "🎲",
      bannerKeyword: "GAMES",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  karafiel: {
    id: "karafiel",
    name: "Karafiel",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "stem",
    repo: "karafiel",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "karafiel.mx",
    hosts: [
      "app.karafiel.mx",
      "api.karafiel.mx",
      "admin.karafiel.mx",
    ],
    infraHosts: [],
    site: {
      category: "Standards",
      track: "self-serve",
      order: 8,
      icon: "📜",
      bannerKeyword: "COMPLIANCE & CFDI",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "contador",
        "despacho",
        "firma",
      ],
      adminTier: "admin",
      checkoutSlug: "karafiel",
    },
  },
  tezca: {
    id: "tezca",
    name: "Tezca",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "stem",
    repo: "tezca",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "tezca.mx",
    hosts: [
      "api.tezca.mx",
      "admin.tezca.mx",
    ],
    infraHosts: [],
    site: {
      category: "Standards",
      track: "self-serve",
      order: 9,
      icon: "⚖️",
      bannerKeyword: "LEGAL OPS",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "community",
        "essentials",
        "institutional",
      ],
      adminTier: "admin",
      checkoutSlug: "tezca",
    },
  },
  avala: {
    id: "avala",
    name: "Avala",
    acronym: "Alineamiento y Verificación de Aprendizajes y Logros Acreditables",
    aliases: [
      "AVALA",
    ],
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "stem",
    repo: "avala",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "avala.studio",
    hosts: [
      "app.avala.studio",
      "admin.avala.studio",
      "api.avala.studio",
    ],
    infraHosts: [],
    site: {
      category: "Standards",
      track: "ecosystem",
      order: 10,
      icon: "🎓",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "institution",
        "issuer",
        "enterprise",
      ],
      adminTier: "admin",
    },
  },
  yantra4d: {
    id: "yantra4d",
    name: "Yantra4D",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "yantra4d",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "yantra4d.com",
    hosts: [
      "app.yantra4d.com",
      "api.yantra4d.com",
      "admin.yantra4d.com",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "ecosystem",
      order: 11,
      icon: "📐",
      bannerKeyword: "PHYGITAL FABRICATION",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "guest",
        "essentials",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
      checkoutSlug: "yantra4d",
    },
  },
  cotiza: {
    id: "cotiza",
    name: "Cotiza",
    aliases: [
      "Cotiza Studio",
    ],
    siteSlug: "cotiza-studio",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "Proprietary",
    layer: "fruit",
    repo: "digifab-quoting",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "cotiza.studio",
    hosts: [
      "api.cotiza.studio",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "ecosystem",
      order: 12,
      icon: "📊",
      bannerKeyword: "QUOTING ENGINE",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "maker",
        "creator-pro",
        "business",
        "enterprise",
      ],
      adminTier: "admin",
      checkoutSlug: "cotiza",
    },
  },
  "pravara-mes": {
    id: "pravara-mes",
    name: "Pravara MES",
    aliases: [
      "Pravara-MES",
    ],
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "pravara-mes",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "mes.madfam.io",
    hosts: [
      "mes-api.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "ecosystem",
      order: 13,
      icon: "⚙️",
      bannerKeyword: "MANUFACTURING",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  voxa: {
    id: "voxa",
    name: "Voxa",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "Apache-2.0",
    layer: "fruit",
    repo: "voxa",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "voxa.madfam.io",
    hosts: [],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 14,
      icon: "🗣️",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "family",
        "clinic",
      ],
      adminTier: "admin",
      checkoutSlug: "voxa",
    },
  },
  "phynd-crm": {
    id: "phynd-crm",
    name: "PhyndCRM",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "phynd-crm",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "phynd.app",
    hosts: [
      "crm.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 15,
      icon: "🤝",
      bannerKeyword: "CLIENT PORTAL & CRM",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  ceq: {
    id: "ceq",
    name: "CEQ",
    lifecycle: "degraded",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "ceq",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "ceq.lol",
    hosts: [
      "app.ceq.lol",
      "api.ceq.lol",
      "ws.ceq.lol",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 16,
      icon: "🎨",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "pro",
        "madfam",
      ],
      adminTier: "admin",
    },
  },
  acervo: {
    id: "acervo",
    name: "Acervo",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "UNLICENSED",
    layer: "fruit",
    repo: "acervo",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "acervo.madfam.io",
    hosts: [],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 17,
      icon: "📚",
      showInBanner: true,
    },
    commerce: {
      tiers: [],
      adminTier: "admin",
    },
  },
  kalya: {
    id: "kalya",
    name: "kalya",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "UNLICENSED",
    layer: "fruit",
    repo: "kalya",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "kalya.app",
    hosts: [
      "www.kalya.app",
      "kalya.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 18,
      icon: "📅",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "free",
        "solo",
        "team",
        "biz",
      ],
      adminTier: "admin",
      checkoutSlug: "kalya",
      tierLabels: {
        free: "Gratis",
        solo: "Solo",
        team: "Equipo",
        biz: "Negocio",
      },
    },
  },
  symbiosis: {
    id: "symbiosis",
    name: "Symbiosis HCM",
    lifecycle: "live",
    lifecycleVerified: "2026-09-05",
    license: "AGPL-3.0",
    layer: "fruit",
    repo: "symbiosis-hcm",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "hcm.madfam.io",
    hosts: [
      "hcm-app.madfam.io",
      "hcm-admin.madfam.io",
      "hcm-api.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 19,
      icon: "🧬",
      showInBanner: false,
    },
    commerce: {
      tiers: [
        "free",
        "team",
        "biz",
      ],
      adminTier: "admin",
      checkoutSlug: "symbiosis",
      tierLabels: {
        free: "Gratis",
        team: "Equipo",
        biz: "Negocio",
      },
    },
  },
  "crea-map": {
    id: "crea-map",
    name: "MAP — Modelo de Acompañamiento Personalizado",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "UNLICENSED",
    layer: "fruit",
    repo: "crea-map",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "crea-map.madfam.io",
    hosts: [],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "ecosystem",
      order: 20,
      icon: "🗺️",
      showInBanner: false,
    },
    commerce: {
      tiers: [
        "membership",
      ],
      adminTier: "admin",
      checkoutSlug: "crea-map",
      tierLabels: {
        membership: "Acceso de equipo",
      },
    },
  },
  nauta: {
    id: "nauta",
    name: "Nauta",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "UNLICENSED",
    layer: "fruit",
    repo: "nauta",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "cto.madfam.io",
    hosts: [
      "crea.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "platform",
      order: 21,
      icon: "🧭",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "erp",
        "vcto",
      ],
      adminTier: "admin",
      tierLabels: {
        erp: "ERP",
        vcto: "vCTO",
      },
    },
  },
  meridian: {
    id: "meridian",
    name: "Meridian",
    lifecycle: "degraded",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "stem",
    repo: "meridian",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    domain: "meridian.madfam.io",
    hosts: [
      "meridian-app.madfam.io",
      "meridian-api.madfam.io",
      "meridian-admin.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Standards",
      track: "ecosystem",
      order: 22,
      icon: "🛂",
      showInBanner: true,
    },
    commerce: {
      tiers: [],
      adminTier: "admin",
    },
  },
  "fashion-cabinet": {
    id: "fashion-cabinet",
    name: "Fashion Cabinet",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "AGPL-3.0",
    layer: "stem",
    repo: "fashion-cabinet",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "fashioncabi.net",
    hosts: [
      "www.fashioncabi.net",
      "fc.madfam.io",
    ],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "ecosystem",
      order: 23,
      icon: "👗",
      showInBanner: true,
    },
    commerce: {
      tiers: [],
      adminTier: "admin",
    },
  },
  factlas: {
    id: "factlas",
    name: "Factlas",
    lifecycle: "live",
    lifecycleVerified: "2026-08-24",
    license: "Proprietary",
    layer: "roots",
    repo: "factlas",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    domain: "factl.as",
    hosts: [
      "api.factl.as",
    ],
    infraHosts: [],
    site: {
      category: "Intelligence",
      track: "ecosystem",
      order: 24,
      icon: "🌎",
      showInBanner: true,
    },
    commerce: {
      tiers: [
        "pilot",
        "analyst",
        "institutional",
      ],
      adminTier: "admin",
    },
  },
  periplo: {
    id: "periplo",
    name: "Periplo",
    lifecycle: "incubating",
    lifecycleVerified: "2026-08-24",
    license: "UNLICENSED",
    layer: "fruit",
    repo: "periplo",
    githubOrg: "madfam-org",
    repoVisibility: "private",
    isPublic: false,
    hosts: [],
    infraHosts: [],
    site: {
      category: "Applications",
      track: "self-serve",
      order: 25,
      icon: "📍",
      showInBanner: false,
    },
    commerce: {
      tiers: [
        "free",
        "essentials",
        "pro",
      ],
      adminTier: "admin",
    },
  },
  "geom-core": {
    id: "geom-core",
    name: "geom-core",
    lifecycle: "incubating",
    lifecycleVerified: "2026-09-04",
    license: "Apache-2.0",
    layer: "stem",
    repo: "geom-core",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    hosts: [],
    infraHosts: [],
    site: {
      category: "Standards",
      track: "ecosystem",
      order: 26,
      icon: "🧮",
      showInBanner: false,
    },
    commerce: {
      tiers: [],
      adminTier: "admin",
    },
  },
  fragua: {
    id: "fragua",
    name: "Fragua",
    lifecycle: "incubating",
    lifecycleVerified: "2026-09-04",
    license: "AGPL-3.0",
    layer: "soil",
    repo: "enclii",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    hosts: [],
    infraHosts: [],
    site: {
      category: "Infrastructure",
      track: "platform",
      order: 27,
      icon: "⚒️",
      showInBanner: false,
    },
    commerce: {
      tiers: [
        "arranque",
        "equipo",
        "escala",
        "dedicada",
      ],
      adminTier: "admin",
      tierLabels: {
        arranque: "Arranque",
        equipo: "Equipo",
        escala: "Escala",
        dedicada: "Dedicada",
      },
    },
  },
  enclii_depot: {
    id: "enclii_depot",
    name: "Enclii Depot",
    lifecycle: "incubating",
    lifecycleVerified: "2026-09-04",
    license: "AGPL-3.0",
    layer: "soil",
    repo: "enclii",
    githubOrg: "madfam-org",
    repoVisibility: "public",
    isPublic: true,
    hosts: [],
    infraHosts: [],
    site: {
      category: "Infrastructure",
      track: "platform",
      order: 28,
      icon: "🗄️",
      showInBanner: false,
    },
    commerce: {
      tiers: [
        "community",
        "pro",
        "premium",
        "madfam",
      ],
      adminTier: "admin",
      tierLabels: {
        community: "Comunidad",
        pro: "Estándar",
        premium: "Alta disponibilidad",
        madfam: "Dedicado",
      },
    },
  },
} as const;

/**
 * Tombstones. A retired brand is kept so a consumer can recognise it and
 * redirect, which is how it stops silently reappearing in a catalog.
 */
export const generatedRetiredProducts = {
  penny: {
    id: "penny",
    name: "PENNY",
    lifecycle: "retired",
    retiredOn: "2026-07-25",
    successorSlug: "selva",
    redirectTo: "https://selva.town",
  },
  sim4d: {
    id: "sim4d",
    name: "Sim4D",
    lifecycle: "retired",
    retiredOn: "2026-08-30",
    successorSlug: "yantra4d",
    redirectTo: "https://yantra4d.com",
  },
  spark: {
    id: "spark",
    name: "SPARK",
    lifecycle: "retired",
    retiredOn: "2026-04-08",
  },
} as const;
