# DocGuard Workflow Template for MADFAM Ecosystem
#
# Copy this file to your repository at:
#   .github/workflows/doc-lint.yml
#
# For more information, see:
#   https://github.com/madfam-org/solarpunk-foundry

name: Documentation Lint

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '*.md'
      - '.env.example'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '*.md'
      - '.env.example'

jobs:
  doc-guard:
    name: DocGuard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run DocGuard
        uses: madfam-org/solarpunk-foundry/.github/actions/doc-guard@main
        with:
          doc-path: './docs'
          strict: true
