# Redis Cluster Setup
# High availability Redis cluster with sentinel monitoring

version: '3.8'

services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: janua-redis-master
    restart: unless-stopped
    command: >
      redis-server
      --port 6379
      --bind 0.0.0.0
      --protected-mode no
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --tcp-backlog 511
      --timeout 0
      --loglevel notice
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
    networks:
      - janua-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Slave 1
  redis-slave-1:
    image: redis:7-alpine
    container_name: janua-redis-slave-1
    restart: unless-stopped
    command: >
      redis-server
      --port 6379
      --bind 0.0.0.0
      --protected-mode no
      --slaveof redis-master 6379
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --tcp-backlog 511
      --timeout 0
      --loglevel notice
      --slave-read-only yes
    ports:
      - "6380:6379"
    volumes:
      - redis_slave_1_data:/data
    depends_on:
      - redis-master
    networks:
      - janua-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Slave 2
  redis-slave-2:
    image: redis:7-alpine
    container_name: janua-redis-slave-2
    restart: unless-stopped
    command: >
      redis-server
      --port 6379
      --bind 0.0.0.0
      --protected-mode no
      --slaveof redis-master 6379
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --tcp-backlog 511
      --timeout 0
      --loglevel notice
      --slave-read-only yes
    ports:
      - "6381:6379"
    volumes:
      - redis_slave_2_data:/data
    depends_on:
      - redis-master
    networks:
      - janua-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: janua-redis-sentinel-1
    restart: unless-stopped
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - redis_sentinel_1_data:/data
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - janua-redis-network

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: janua-redis-sentinel-2
    restart: unless-stopped
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - redis_sentinel_2_data:/data
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - janua-redis-network

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: janua-redis-sentinel-3
    restart: unless-stopped
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis-sentinel.conf:/etc/redis/sentinel.conf
      - redis_sentinel_3_data:/data
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - janua-redis-network

  # Redis Cluster Proxy (for client load balancing)
  redis-proxy:
    image: haproxy:2.8-alpine
    container_name: janua-redis-proxy
    restart: unless-stopped
    ports:
      - "6382:6379"  # Proxy port
      - "8405:8404"  # HAProxy stats
    volumes:
      - ./redis-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - janua-redis-network

  # Redis Insight (Redis GUI for monitoring)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: janua-redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    networks:
      - janua-redis-network

volumes:
  redis_master_data:
    driver: local
  redis_slave_1_data:
    driver: local
  redis_slave_2_data:
    driver: local
  redis_sentinel_1_data:
    driver: local
  redis_sentinel_2_data:
    driver: local
  redis_sentinel_3_data:
    driver: local
  redis_insight_data:
    driver: local

networks:
  janua-redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16